### ISSUE TITLE
Not working when using sentry-sdk

### ISSUE THREAD

**Issue by kefonseca** [Archmonger/ServeStatic#25]
### Python Version

3.10.12

### Django Version

4.2.13

### Package Version

1.2.0

### Description

An exception is raised when using sentry-sdk, working without problems when sentry-sdk is not used.

It seems to be related to the servestatic middleware not being sync capable but I'm not totally sure. 

`gunicorn --workers 1 --bind :8000 --max-requests 1000 --max-requests-jitter 100 -k uvicorn.workers.UvicornWorker config.asgi:application`

```
[2024-09-03 16:26:26 -0400] [3656841] [INFO] Starting gunicorn 23.0.0
[2024-09-03 16:26:26 -0400] [3656841] [INFO] Listening at: http://0.0.0.0:8000 (3656841)
[2024-09-03 16:26:26 -0400] [3656841] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-09-03 16:26:26 -0400] [3656842] [INFO] Booting worker with pid: 3656842
[2024-09-03 15:26:29 -0500] [3656842] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/usuario/ARI/FacturaElectronica/backend-publico-django/config/asgi.py", line 16, in <module>
    application = get_asgi_application()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/django/core/asgi.py", line 13, in get_asgi_application
    return ASGIHandler()
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 146, in __init__
    self.load_middleware(is_async=True)
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 61, in sentry_patched_load_middleware
    return old_load_middleware(*args, **kwargs)
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/django/core/handlers/base.py", line 61, in load_middleware
    mw_instance = middleware(adapted_handler)
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py", line 130, in __init__
    self._inner = middleware(get_response, *args, **kwargs)
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/servestatic/middleware.py", line 84, in __init__
    raise ValueError(
ValueError: ServeStaticMiddleware requires an async compatible version of Django.
```

**Comment by Archmonger** [comment]
This seems to be a bug with Sentry SDK. They appear to be patching Django's middleware for analytics purposes
```bash
  File "/home/usuario/.virtualenvs/backend_ff_dj4/lib/python3.10/site-packages/sentry_sdk/integrations/django/middleware.py",
  line 61, in sentry_patched_load_middleware
    return old_load_middleware(*args, **kwargs)
```
But it seems like they aren't taking proper consideration for Django async middleware.

ServeStatic >= 1.2 only runs in async mode in order to avoid [existing bugs within Django/Asgiref](https://github.com/Archmonger/ServeStatic/pull/13#issuecomment-2312658999).

You should open this issue on [their GitHub repository](https://github.com/getsentry/sentry-python).

**Comment by Archmonger** [comment]
Closing this since it's an issue with Sentry-SDK. An issue should be opened on their repo.
