### ISSUE TITLE
Crash if `STATIC_ROOT` is a `pathlib.Path`

### ISSUE THREAD

**Issue by stumpylog** [Archmonger/ServeStatic#29]
### Python Version

3.11

### Django Version

4.2

### Package Version

2.0.0

### Description

If `STATIC_ROOT` is defined as a `Path` object, running `collectstatic` will fail inside servestatic as per the below traceback:

```python
Traceback (most recent call last):
  File "/home/user/projects/paperless-ngx/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 148, in collect
    for original_path, processed_path, processed in processor:
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/servestatic/storage.py", line 95, in post_process
    self.add_stats_to_manifest()
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/servestatic/storage.py", line 102, in add_stats_to_manifest
    "stats": self.stat_static_root(),
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/servestatic/storage.py", line 124, in stat_static_root
    return {path[len(static_root) + 1 :]: stat for path, stat in stats.items()}
  File "/home/user/projects/paperless-ngx/.venv/lib/python3.10/site-packages/servestatic/storage.py", line 124, in <dictcomp>
    return {path[len(static_root) + 1 :]: stat for path, stat in stats.items()}
TypeError: object of type 'PosixPath' has no len()
```

**Comment by Archmonger** [comment]
Thank you for the bug report!

v2.0.1 has been released which resolves this issue.
